# Site settings
title: FIRST 2015 CERT-Verbund
email: first2015@cert-verbund.de
description: > # this means to ignore newlines until "baseurl:"
        Information for FIRST 2015 attendees about restaurants, pubs, activities provided by the local teams.
baseurl: "/first2015" # the subpath of your site, e.g. /blog/
#url: "http://first2015.cert-verbund.de" # the base hostname & protocol for your site
url: "http://cert-verbund.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb

# Build settings
markdown: kramdown

mapping:
    provider: openstreetmap
    zoom: 10
    dimensions:
        width: 600
        height: 400

    locations:
                - title: foo
                  latitude: 10
                  longitude: 10
                - title: bar
                  latitude: -10
                  longitude: -10
